---
## _config.yml
title: Alexander Magnusson
description: Software Engineer
url: https://portfolio.alexandermagnusson.net
baseurl: ""

# Author
author:
  name: Alexander Magnusson
  email: magnusson.alex@gmail.com
  github: Alexandoooor
  linkedin: alexander-magnusson-0233a4114

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

permalink: /posts/:title/

# Collections
collections:
  projects:
    output: false

# Exclude
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Pagination
plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/posts/page:num/"
